Repository compomics/ms2pip, pull requests merged in 2021-01, with the labels that each got.

#109 fix parsing C-term modifications
  ms2pip/peptides.py
Labels: bug

#121 Update fasta2speclib_config.json
  fasta2speclib/fasta2speclib_config.json
Labels: bug

#122 Add tests and deployment for Python 3.9
  .github/workflows/build_and_publish.yml
  .github/workflows/test.yml
Labels: deployment

#123 Exit(1) after exception is logged in main
  ms2pip/__main__.py
Labels: enhancement

#124 v3.6.3
  setup.py
Labels: deployment

#127 Update tests, use cibuildwheel to build wheels
  .github/workflows/build_and_publish.yml
  tests/test_config_parser.py
  tests/test_features.py
  tests/test_predictions.py
  tests/test_retention_time.py
  tests/test_spectrum_output.py
Labels: deployment

#129 Document supported and allowed extensions for config file
  README.md
  ms2pip/__main__.py
  ms2pip/config_parser.py
Labels: documentation, enhancement
