Repository compomics/ms2pip, pull requests merged in 2024-11, with the labels that each got.

#232 Add correlate_single usage mode (API only)
  docs/source/usage.rst
  ms2pip/core.py
Labels: feature

#225 Update URL to download models
  ms2pip/_utils/xgb_models.py
Labels: enhancement

#237 Remove musllinux builds (no ms2rescore-rs builds)
  pyproject.toml
Labels: deployment

#238 CI: Fix build and publish workflow
  .github/workflows/build_and_publish.yml
Labels: deployment
